version: "3.8"

services:
  backend:
    image: auth-api:latest
    container_name: auth-api
    ports:
      - "8083:8083"
    networks:
      - app-net

  frontend:
    image: frontend:latest
    container_name: frontend
    ports:
      - "8084:80"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
